# Generated by Django 3.2 on 2023-05-17 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                db_index=True,
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        flags=0,
                        message='Недопустимое имя пользователя.',
                        regex='^[\\w.@+-]+$',
                    )
                ],
            ),
        ),
    ]
