# Generated by Django 3.2 on 2023-05-14 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0002_comment_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='title',
        ),
    ]
